#Evaluate the machine learning model you just created.

#The metrics generated by this query tell us how well the model is likely to perform.
WITH eval_table AS (
SELECT
 category,
 resolutiontime as label
FROM
  helpdesk.issues
)
SELECT
  *
FROM
  ML.EVALUATE(MODEL helpdesk.predict_eta_v0,
    TABLE eval_table);

#Using the evaluation metrics, we can see that the model doesnt perform very well. 
#When the r2_score and explained_variance metrics are close to 0, our algorithm is having difficulty distinguishing the signal in our data from the noise.